# 服务运行配置
server:
  host: 0.0.0.0
  port: 13001
  env: dev

# mysql配置
mysql:
  host: 127.0.0.1
  port: 3306
  db_name: summer_blog
  username: root
  password: rootROOT@1234
  # dev环境输出sql日志
  log_level: dev

# 日志配置
logger:
  level: info #日志等级
  prefix: "[summer-blog]" #日志前缀
  file_path: log #日志生成的目录名
  show_line: true #是否显示行号
  log_in_console: true #是否显示操作文件路径
