# 服务运行配置
server:
  host: 0.0.0.0
  port: 13001
  env: debug  #debug|release
  db_type: mysql

# postgresql配置
pgsql:
  host: 127.0.0.1
  port: 5432
  db_name: summer_blog
  username: summer
  password: summer
  # dev环境输出sql日志
  log_level: dev
  # 是否自动生成表结构
  create_table: true

# mysql配置
mysql:
  host: 127.0.0.1
  port: 3306
  db_name: summer_blog
  username: root
  password: rootROOT@1234
  # dev环境输出sql日志
  log_level: dev
  # 是否自动生成表结构
  create_table: true

# 日志配置
logger:
  level: debug #日志等级 info warning debug
  prefix: "[summer-blog]" #日志前缀
  file_path: log #日志生成的目录名
  show_line: true #是否显示行号
  log_in_console: true #是否显示操作文件路径
