server:
  host: 0.0.0.0
  port: 13001
  env: debug
  db_type: pgsql
mysql:
  host: 127.0.0.1
  port: 3306
  db_name: summer_blog
  username: root
  password: rootROOT@1234
  log_level: dev
  create_table: false
pgsql:
  host: 127.0.0.1
  port: 5432
  db_name: summer_blog
  username: summer
  password: summer
  log_level: dev
  create_table: false
logger:
  level: debug
  prefix: '[summer-blog]'
  # 日志文件存放目录
  file_path: logs/
  # 每天生成新的日志文件
  file_split_day: 1
  # 最多保留30天
  file_max_age: 30
  show_line: true
  log_in_console: true
site_info:
  created: "2023-03-08"
  bei_an: 备案号
  title: Blogs
  version: 1.0.0
  email: 1143967454@qq.com
  name: zero9501
  work: 服务端开发
  addr: 广州
  slogan: Blogs
  web: https://zlx2019.github.io
  gitee: https://gitee.com
  github: https://github.com/zlx2019
qq:
  app_id: xxx
  key: xxx
  redirect: xxxxd
email:
  host: xxx
  port: xxx
  user: xxx
  password: xxx
  sender: 发件人
  use_ssl: false
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: zero
qi_niu:
  access_key: xxx
  secret_key: xxx
  bucket: xxx
  domain: xxx
  zone: xxx
  size: 5
